<a href="https://colab.research.google.com/github/aelukin/ML_ITMO/blob/main/watch_market_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Монтируем диск, задаем директорию

In [206]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [207]:
%cd gdrive/MyDrive/ML\ ITMO

[Errno 2] No such file or directory: 'gdrive/MyDrive/ML ITMO'
/content/gdrive/MyDrive/ML ITMO


Импортируем библиотеки

In [208]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Импортируем датасет

In [209]:
path='Watches.csv'
data=pd.read_csv(path, index_col='Unnamed: 0')

<ipython-input-209-50ca43d5d0b5>:2: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv(path, index_col='Unnamed: 0')


# Часть 1. Проверка и очистка данных

In [210]:
data.head()

name     price  \
0  Audemars Piguet Royal Oak Offshore Chronograph...   $43,500   
1  Audemars Piguet Royal Oak Selfwinding\n39mm Bl...   $71,500   
2  Audemars Piguet Royal Oak Chronograph\nBlue Di...   $79,191   
3  Audemars Piguet Royal Oak Chronograph\nSelfwin...  $108,000   
4  Audemars Piguet Royal Oak Offshore Chronograph...   $27,500   

             brand                           model                   ref  \
0  Audemars Piguet  Royal Oak Offshore Chronograph  26237ST.OO.1000ST.01   
1  Audemars Piguet           Royal Oak Selfwinding  15300ST.OO.1220ST.02   
2  Audemars Piguet           Royal Oak Chronograph               26331ST   
3  Audemars Piguet           Royal Oak Chronograph  26715ST.OO.1356ST.01   
4  Audemars Piguet  Royal Oak Offshore Chronograph  26170ST.OO.1000ST.01   

        mvmt  casem bracem                   yop       cond  \
0        NaN    NaN    NaN                  2019     Unworn   
1        NaN    NaN    NaN                  2012  Very good   
2  Automatic  Steel  Steel               Unknown     Unworn   
3  Automatic  Steel  Steel  2022 (Approximation)        New   
4  Automatic  Steel  Steel               Unknown  Very good   

                  sex        size condition  
0  Men's watch/Unisex       42 mm       NaN  
1  Men's watch/Unisex       39 mm       NaN  
2                 NaN       41 mm       NaN  
3  Men's watch/Unisex       38 mm       NaN  
4  Men's watch/Unisex  42 x 54 mm       NaN

In [211]:
data.tail()

name    price   brand  \
6438  Zenith Defy El Primero\n21 TITANIUM 95.9000.90...   $9,790  Zenith   
6439  Zenith Chronomaster Sport\n41mm White 03.3100....   $8,450  Zenith   
6440   Zenith El Primero\n50th Anniversary A386 Limited  $16,500  Zenith   
6441  Zenith Chronomaster Sport\nWhite Dial Chronogr...   $9,000  Zenith   
6442  Zenith El Primero Chronomaster\n03.2040.400/69...   $6,833  Zenith   

                        model                    ref       mvmt  casem  \
6438          Defy El Primero  95.9000.9004/78.M9000        NaN    NaN   
6439       Chronomaster Sport  03.3100.3600/69.M3100        NaN    NaN   
6440               El Primero    30.A386.400/69.C807        NaN    NaN   
6441       Chronomaster Sport  03.3100.3600/69.M3100        NaN    NaN   
6442  El Primero Chronomaster                    NaN  Automatic  Steel   

       bracem                   yop       cond                 sex   size  \
6438      NaN                  2022  Very good  Men's watch/Unisex  44 mm   
6439      NaN  2021 (Approximation)  Very good  Men's watch/Unisex  41 mm   
6440      NaN                  2019  Very good  Men's watch/Unisex  38 mm   
6441      NaN                  2021     Unworn  Men's watch/Unisex  41 mm   
6442  Leather                  2019  Very good                 NaN  42 mm   

     condition  
6438       NaN  
6439       NaN  
6440       NaN  
6441       NaN  
6442       NaN

Проверка данных

In [212]:
data.columns

Index(['name', 'price', 'brand', 'model', 'ref', 'mvmt', 'casem', 'bracem',
       'yop', 'cond', 'sex', 'size', 'condition'],
      dtype='object')

In [213]:
data.shape

(284491, 13)

In [214]:
data.dtypes

name         object
price        object
brand        object
model        object
ref          object
mvmt         object
casem        object
bracem       object
yop          object
cond         object
sex          object
size         object
condition    object
dtype: object

In [215]:
data.isna().sum()

name          72585
price           406
brand           131
model         30466
ref           43152
mvmt         196685
casem        164271
bracem       174896
yop             134
cond          75987
sex           95805
size          23597
condition    212922
dtype: int64

In [216]:
data.describe()

name             price  \
count                                              211906            284085   
unique                                             148689             36830   
top     Omega Speedmaster Professional Moonwatch\nCo-A...  Price on request   
freq                                                  171             14259   

         brand        model     ref       mvmt   casem  bracem      yop  \
count   284360       254025  241339      87806  120220  109595   284357   
unique      28          948   33223          3      17      23      410   
top      Rolex  Datejust 36  126334  Automatic   Steel   Steel  Unknown   
freq     72484         9473    2081      65600   75793   49605    95957   

             cond                 sex    size  condition  
count      208504              188686  260894      71569  
unique          7                   2    6699          7  
top     Very good  Men's watch/Unisex   40 mm  Very good  
freq        71604              158841   34254      36136

In [217]:
data['brand'].unique()

array(['Audemars Piguet', 'Cartier', 'Tudor', nan, 'Breitling', 'Oris',
       'Richard Mille', 'Hublot', 'IWC', 'Jaeger-LeCoultre', 'Longines',
       'Omega', 'Panerai', 'Patek Philippe', 'Rolex', 'Seiko', 'Sinn',
       'Edox', 'NOMOS', 'Zenith', 'Tissot', 'Hamilton', 'Meistersinger',
       'Rado', 'Montblanc', 'TAG Heuer', 'Ebel', 'A. Lange & Söhne',
       'Vacheron Constantin'], dtype=object)

In [218]:
data['mvmt'].unique()

array([nan, 'Automatic', 'Manual winding', 'Quartz'], dtype=object)

In [219]:
data['casem'].unique()

array([nan, 'Steel', 'Titanium', 'White gold', 'Ceramic', 'Rose gold',
       'Yellow gold', 'Gold/Steel', 'Platinum', 'Carbon', 'Red gold',
       'Tantalum', 'Aluminum', 'Bronze', 'Plastic', 'Silver', 'Palladium',
       'Tungsten'], dtype=object)

In [220]:
data['bracem'].unique()

array([nan, 'Steel', 'Rubber', 'Crocodile skin', 'White gold', 'Ceramic',
       'Rose gold', 'Yellow gold', 'Titanium', 'Calf skin', 'Gold/Steel',
       'Leather', 'Platinum', 'Satin', 'Textile', 'Red gold',
       'Lizard skin', 'Plastic', 'Aluminium', 'Silicon', 'Shark skin',
       'Silver', 'Snake skin', 'Ostrich skin'], dtype=object)

In [221]:
data['cond'].unique()

array(['Unworn', 'Very good', 'New', 'Good', 'Fair', nan, 'Poor',
       'Incomplete'], dtype=object)

In [222]:
data['sex'].unique()

array(["Men's watch/Unisex", nan, "Women's watch"], dtype=object)

In [223]:
data['size'].unique()

array(['42 mm', '39 mm', '41 mm', ..., '40 x 10.75 mm', '46 x 17 mm',
       '48 x 57.5 mm'], dtype=object)

In [224]:
data['condition'].unique()

array([nan, 'Very good', 'Unworn', 'Good', 'Fair', 'New', 'Poor',
       'Incomplete'], dtype=object)

Ищем и удаляем дублирующиеся ячейки

In [225]:
data.isna().sum()

name          72585
price           406
brand           131
model         30466
ref           43152
mvmt         196685
casem        164271
bracem       174896
yop             134
cond          75987
sex           95805
size          23597
condition    212922
dtype: int64

In [226]:
data.duplicated().sum()

11398

In [227]:
data=data.drop_duplicates()

In [228]:
data.describe()

name             price  \
count                                              206862            272783   
unique                                             148689             36830   
top     Omega Speedmaster Professional Moonwatch\nCo-A...  Price on request   
freq                                                  169             11934   

         brand        model     ref       mvmt   casem  bracem      yop  \
count   273028       243114  230967      84667  113932  104257   273025   
unique      28          948   33223          3      17      23      410   
top      Rolex  Datejust 36  126334  Automatic   Steel   Steel  Unknown   
freq     66130         8357    1731      63144   72373   47387    91387   

             cond                 sex    size  condition  
count      203593              184005  250359      65258  
unique          7                   2    6699          7  
top     Very good  Men's watch/Unisex   40 mm  Very good  
freq        71007              155235   32650      33267

In [229]:
data['condition'].isna().sum()+data['cond'].isna().sum()

277335

Идентифицированные проблемы датасета:

*   Колонки 'cond' and 'condition'. Есть основания полагать, что по какой-то причине значения "состояния" разбиты на две колонки, которые необходимо объединить вручную.
*   Цена 'price' в текстовом формате
*   Лишняя информация в столбце 'size'
*   Столбец с годом производства 'yop' требует дополнительной проверки







In [230]:
data['cond'] = data['cond'].fillna('')
data['condition'] = data['condition'].fillna('')
data['condition_summed']=data['cond'].astype(str)+data['condition'].astype(str)

In [231]:
data.describe()

name             price  \
count                                              206862            272783   
unique                                             148689             36830   
top     Omega Speedmaster Professional Moonwatch\nCo-A...  Price on request   
freq                                                  169             11934   

         brand        model     ref       mvmt   casem  bracem      yop  \
count   273028       243114  230967      84667  113932  104257   273025   
unique      28          948   33223          3      17      23      410   
top      Rolex  Datejust 36  126334  Automatic   Steel   Steel  Unknown   
freq     66130         8357    1731      63144   72373   47387    91387   

             cond                 sex    size condition condition_summed  
count      273093              184005  250359    273093           273093  
unique          8                   2    6699         8                8  
top     Very good  Men's watch/Unisex   40 mm                  Very good  
freq        71007              155235   32650    207835           104274

In [232]:
data['condition'].isna().sum()+data['cond'].isna().sum()

0

In [237]:
data.condition.value_counts()

              207835
Very good      33267
Unworn         12453
New            10186
Good            8004
Fair            1300
Poor              45
Incomplete         3
Name: condition, dtype: int64

In [234]:
data.cond.value_counts()

Very good     71007
              69500
New           65565
Unworn        32182
Good          27203
Fair           7446
Poor            148
Incomplete       42
Name: cond, dtype: int64

In [238]:
data.condition_summed.value_counts().sum()

273093